### ISSUE TITLE
error 'Target size (torch.Size([8])) must be the same as input size (torch.Size([8, 2]))' with 'bert_for_cls'

### ISSUE THREAD

**Issue by tennnx** [DaSE4Good/EfficientTools#21]
运行bert_for_cls的main.py之后报这个错“ValueError: Target size (torch.Size([8])) must be the same as input size (torch.Size([8, 2]))”，有同学知道怎么解决吗，万分感谢！

**Comment by zzyzeyuan** [comment]
报错原因写的很清楚，你可以试试reshape, view, squeeze等操作，对齐tensor维度后应该就能解决了。
